name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher le contenu du répertoire
        run: ls -R ..
      - name: Afficher le chemin actuel
        run: ls -R .
      - name: Installer les dépendances
        working-directory: .
        run: npm install
      - name: Exécuter les tests
        run: npm test
