name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Installer les dépendances
        working-directory: /home/runner/work/devops-mini-proj-tdd-greetings/package.json
        run: npm install
      - name: Exécuter les tests
        run: npm test
